### ISSUE TITLE
InvalidURIEncoding should not raise 404?

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/rack-cleanser#2]
Currently, when it detects that the request param has bad encoding, it raises `ActionController::RoutingError`.
Question is, is this appropriate?  Should some other HTTP responses be used?

**Comment by ronaldtse** [comment]
According to https://tools.ietf.org/html/rfc7231#section-6.5.1

>  6.5.1.  400 Bad Request
> 
>    The 400 (Bad Request) status code indicates that the server cannot or
>    will not process the request due to something that is perceived to be
>    a client error (e.g., malformed request syntax, invalid request
>    message framing, or deceptive request routing).

It sounds an invalid URI encoding is a client error and returning 400 is appropriate.

**Comment by ribose-jeffreylau** [comment]
Cool.  I think we should then make sure it returns 400 and not 404.
