### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by skalee** [riboseinc/rack-cleanser#23]
I believe this gem is not thread-safe. Here an instance variable is set, but this may cause a race condition as the object instance is assigned to particular rack stack which can be traversed by threads concurrently.

https://github.com/riboseinc/rack-cleanser/blob/e32b1b3fa9b4446bd2ea41a779bc7863414c12de/lib/rack/cleanser/param_length_limiter.rb#L67

**Comment by ronaldtse** [comment]
We should keep it thread safe for sure. Thanks @skalee !
