### ISSUE TITLE
What's the purpose of check on authenticity_token param?

### ISSUE THREAD

**Issue by skalee** [riboseinc/rack-cleanser#25]
I wonder what's the purpose of these 4 lines

https://github.com/riboseinc/rack-cleanser/blob/630c0dda9503d771f7219eee63a07076807d7260/lib/rack/cleanser/invalid_uri_encoding.rb#L88-L91

The `request_params` variable holds, as its name says, request parameters specified via query string or request body, not `Authorization` HTTP header. I suppose this check is application-specific, and should be removed from `Rack::Cleanser`. Other applications may name authentication parameter differently (e.g. `access_token`), or utilize authorization header instead.

**Comment by ronaldtse** [comment]
Yes @skalee you are absolutely right. We should extract this to the initialization configuration.

**Comment by skalee** [comment]
You mean application configuration or cleanser configuration? I mean, should gem support such checks at all? I think not.

**Comment by ronaldtse** [comment]
@skalee There should be a way for user to specify (e.g. When creating the Cleanser as Rails middleware) to enforce what is a valid parameter to accept. For example, specifying `access_token` must be a String. That's what I meant by using the RackAttack syntax allowing users to specify.

**Comment by skalee** [comment]
IMHO if we're going to add some more advanced parameter constraints, then perhaps it should be done in controllers. I mean some ActionController enhancement like Strong Parameters gem. That would allow for cleaner and per-controller configuration.

Unless there is some important reason to do that before some middleware or Rails router?

**Comment by skalee** [comment]
FYI https://github.com/nicolasblanco/rails_param — some gem which does it, and perhaps requires some warmth.

**Comment by ribose-jeffreylau** [comment]
https://github.com/nicolasblanco/rails_param looks like it'd do the job, however it doesn't seem to support Rails 5?

**Comment by skalee** [comment]
@ribose-jeffreylau It doesn't seem to. Furthermore, it has plenty of open pull requests, and only 1 non-trivial commit merged to master over last year. I am not saying that going with that gem is a good idea. I am saying that any advanced parameters validation would be better done in Rails controllers, and the aforementioned gem roughly (very roughly) describes what I mean. Validating action parameters in controllers has plenty of benefits:

1. Much more maintainable, parameter definition is kept in the same class as action definition, or Strong Parameters constraints.
2. Any content type works great, be it `application/x-www-form-urlencoded`, or multipart form, or even JSON.
3. Rails' code reloading works just great, you don't need to reload application because you've just added another parameter.
4. Same setup for all Rails environments.
5. Way easier to test for a Rails application developer (these parameter constraints should be tested as well!).

That said, after some thinking, I believe that what you actually want to achieve is to validate given collection (here action parameters hash) against some schema. And that perhaps we should look for or develop a more generic gem which is focused on that.

I found a [json-schema](https://github.com/ruby-json-schema/json-schema) gem which serves for this purpose (it validates not only JSONs but also Ruby collections).  However, it seems bit complicated in use as schema definitions are pretty large and confusing. But if you guys like the idea in general, I think I could think of something more straightforward.

**Comment by ribose-jeffreylau** [comment]
@skalee Thanks for the detailed info!

I agree that having the schema (if we're going for it) in the controllers would be more maintainable.  It also seems like it could be a Strong Parameters library but for header fields.
Schema definition for [json-schema](https://github.com/ruby-json-schema/json-schema) is indeed pretty large...

Just a question --- IIUC, if we were to use such kind of parameter validation, standard header fields would be validated using a schema that's typically defined in some core classes like ApplicationController?

**Comment by skalee** [comment]
@ribose-jeffreylau actually, AFAIU it has nothing to do with header files.

Currently, the Rack::Cleanser middleware checks several things:

1. that encoding of some headers is correct
2. that GET and POST params are encoded correctly
3. that request parameter length is within specified constraints
4. that `authenticity_token` parameter, if exists, is a scalar, not collection

I've created this issue because in my opinion the last check is application-specific.  It has evolved in a broader discussion which I guess now covers 3. and 4.  But it is still limited to request parameters, not headers in general, neither to encoding.

I know nothing about similar requirements about headers in general.

**Comment by ribose-jeffreylau** [comment]
@skalee  You are absolutely correct.
I like the idea of a simplified json-schema inside controllers.  How should we go about it?

**Comment by ronaldtse** [comment]
JSON-schema is quite straightforward, but I wonder if a Ruby DSL is more flexible and expressive?

**Comment by skalee** [comment]
@ronaldtse For sure. Think of RSpec matchers. At the moment I'm thinking about sth like that:

```ruby
{
  :authenticity_token => String,
  :user_ids => [Integer],
  :some => {:deep => {:hash => String}},
  :validated_with_regexp => /[a-z]{6}/,
  :custom_and_complicated => here_goes_some_custom_matcher(),
}
```

Most of that can be easily described without using any custom matchers. At the moment I'm not yet sure how to denote whether given param is required or optional. Perhaps we could borrow the idea of compound matchers from RSpec:

```ruby
  :required_and_validated_with_regexp => required() & /[a-z]{6}/,
```

But if we want to go with compound matchers, we need to have some default matcher so that we can override `&` and `|` operators. I mean that following:

```ruby
  :authenticity_token => String,
  :authenticity_token => param(String),
```

should be equivalent. However, the `param(String)`, although longer, is sometimes beneficial as it supports `|` and `&` operators:

```ruby
  :authenticity_token => String & param(/abcd/), # bad, we don't want to define `String::&`
  :authenticity_token => param(String) & param(/abcd/), # good
  :authenticity_token => param(String) & /abcd/, # also good, actually
```

**Comment by ronaldtse** [comment]
@skalee this looks really good! Let's proceed with this direction :-)

**Comment by skalee** [comment]
Then I'm starting a new gem for that. Regarding gem name, any ideas? Maybe "(Rails) Parameter Constraints"? Or "Stronger Parameters"?

**Comment by skalee** [comment]
Just created https://github.com/riboseinc/stronger_parameters. I'm open for rename if someone got better one.

**Comment by ronaldtse** [comment]
Some on top of my head: "structured_parameters", "parameters_validation"

@ribose-jeffreylau ?

**Comment by skalee** [comment]
Parameter has been removed in #35. Closing.
