### ISSUE TITLE
Set up Travis, .rubocop.yml, etc.

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/rack-cleanser#4]

**Comment by ronaldtse** [comment]
@skalee are we done with this one? Thanks!

**Comment by skalee** [comment]
@ronaldtse Not really, I've just added few more Ruby versions to Travis build matrix, and got failures.

Also, since we have Code Climate enabled, do we want test coverage reports from it?

**Comment by skalee** [comment]
Builds for older rubies (2.3+) are now fixed.

**Comment by ronaldtse** [comment]
Just enabled code climate!

**Comment by skalee** [comment]
@ronaldtse I need a token to upload test coverage, and you have privileges to obtain it. Instructions are here: https://docs.codeclimate.com/docs/finding-your-test-coverage-token

You can either paste token here (Code Climate does not seem to consider it a sensitive data, although they don't say it straight) so I can add it to `.travis.yml`, or set `CC_TEST_REPORTER_ID` environment variable on Travis settings page: https://travis-ci.org/riboseinc/rack-cleanser/settings.

**Comment by skalee** [comment]
@ronaldtse ?

**Comment by ronaldtse** [comment]
Here it is: 53b004e6b885ec7f4c557dc8eab62ef182a2f498730b952d0f6b668b507bbef8

**Comment by skalee** [comment]
Done.
