### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by skalee** [riboseinc/rack-cleanser#9]
39 of 78 specs (typically for `Rack::Cleanser.limit_param_length`) do fail on Ruby 2.4.1 + Rails 5 (and possibly on others as well). No extra setup was performed. Either fix them or add documentation to describe setup.

**Comment by skalee** [comment]
Okay, so it looks like tests are failing because of some rescue clause which prints some debug info but doesn't re-raise the exception. I believe this wasn't intentional, and I can remove that debug output. See #11, however I'm not merging-in yet, just in case these debug notes should be preserved for some reason.

**Comment by ronaldtse** [comment]
Got it, @ribose-jeffreylau will confirm you this. Thanks!

**Comment by ribose-jeffreylau** [comment]
Merged. Thanks @skalee !
